name: gnome-favorites-edit
version: 0.0.1
summary: Edit dash favorites of gnome-shell.
description: |
  CLI app of dash favorites editor for gnome-shell.
grade: devel
confinement: classic

apps:
  gnome-favorites-edit:
    command: bin/gnome-favorites-edit
#    environment:
#      GI_TYPELIB_PATH: $SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
#    plugs:
#      - gsettings

parts:
  gnome-favorites-edit-cli:
    plugin: python
    python-version: python3
    stage-packages:
      - libc6
      - libgirepository1.0-dev
      - gir1.2-glib-2.0
      - python3-gi
    source: ./src/
