defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: snapcore/snapcraft:stable
version: 2
workflows:
  version: 2
  commit:
    jobs:
      - build
jobs:
  build:
    <<:  *defaults
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt update
      - run:
          name: Build snap
          command: snapcraft
      - run:
          name: Move artifacts
          command: "mkdir ./out && cp *.snap ./out/"
      - store_artifacts:
          path: ./out
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./out
