version: 2
workflows:
  version: 2
  commit:
    jobs:
      - build-fedora
      - build-ubuntu
jobs:
  build-fedora:
    working_directory: ~/fedora
    docker:
      - image: alanfranz/docker-rpm-builder-configurations:fedora-27
    steps:
      - run: dnf update -y
      - checkout
      - run:
          name: Build .rpm package
          command: python setup.py bdist_rpm
      - store_artifacts:
        path: ./
  build-ubuntu:
    working_directory: ~/ubuntu
    docker:
      - image: debuild/trusty
    steps:
      - run: apt-get update && apt-get dist-upgrade -y
      - checkout
      - run:
          name: Build .deb package
          command: python setup.py --command-packages=stdeb.command bdist_deb
      - store_artifacts:
        path: ./
